apiVersion: v1
kind: Secret
metadata:
  name: backend-{{ include "sample-application-chart.fullname" . }}-secret
type: Opaque
data:
  DB_USERNAME: {{ .Values.backend.database.username | b64enc | quote }}
  BD_PASSWORD: {{ .Values.backend.database.password | b64enc | quote }}