---
apiVersion: v1
kind: Service
metadata:
  name: webserver-{{ include "sample-application-chart.fullname" . }}
  labels:
    {{- include "sample-application-chart.labels" . | nindent 4 }}
spec:
  selector:
    app:  webserver-{{ include "sample-application-chart.fullname" . }}
  type: "{{ .Values.service.type }}"
  ports:
    - name: http
      port: {{ .Values.webserver.container.port}}
      targetPort: {{ .Values.webserver.container.port}}
      protocol: TCP
